version: '3'
services:
  client:
    container_name: client
    restart: always
    build: ./client
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app  
  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - "mongo"
  mongo:
    container_name: mongo
    image: "mongo"
    ports:
      - "27017:27017"
  adminmongo:
    container_name: adminmongo
    image: mrvautin/adminmongo
    ports:
      - 1234:1234
    environment:
      - HOST=0.0.0.0